### ISSUE TITLE
Add to opam

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ogene#6]

**Comment by ihodes** [comment]
opam file added in https://github.com/hammerlab/ogene/commit/5c4d6ce3c9371988fb56162e0c165b5698c72fd2

Not sure this is worth adding to opam repo proper; maybe once there's some more stuff in here.

**Comment by rleonid** [comment]
If you were so inclined, maybe the administrators would accept this tool in [hampam](https://github.com/hammerlab/biopam).

**Comment by ihodes** [comment]
Good idea: https://github.com/hammerlab/biopam/pull/2
